displayName=Pet chance tracker
author=KingCowNat
description=Tracks cumulative chance of receiving a skilling pet
tags=skilling,pet,tracker,chance,
version=0.1
plugins=com.petchancetracker.PetChanceTrackerPlugin
build=standard